
language: go

sudo: false

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - master

script:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /usr/local/bin/dep
  - chmod +x /usr/local/bin/dep
  - dep ensure
  - go test -v -race $(go list ./... | grep -v vendor)
